version: '3.8'

services:
  db:
    image: postgres:15  # <--- Docker la descarga solo
    volumes:
      - postgres_data:/var/lib/postgresql/data # <--- PERSISTENCIA: Para que no se borren tus datos al apagar Docker
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: . # <--- Busca el Dockerfile en la carpeta actual
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code # <--- HOT RELOAD: Si cambias código en tu PC, se refleja en el contenedor sin reiniciar
    ports:
      - "8000:8000" # <--- Conecta el puerto del contenedor con tu navegador
    environment:
      # Aquí pasamos las variables a la "computadora" donde corre Django
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST} # <--- IMPORTANTE: Aquí se usa el nombre del servicio 'db' como dirección
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db # <--- Le dice a Docker que levante la base de datos antes que Django

volumes:
  postgres_data: # <--- Define el espacio donde se guardarán los datos de Postgres